drop table mobile_room_info;

CREATE TABLE `mobile_room_info` (
  `UID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '고유 ID',
  `PROJ_NO` varchar(20) NOT NULL COMMENT '호선 (예: SN2426)',
  `SCHEDULERINFOUID` int(11) DEFAULT NULL COMMENT '스케줄러 정보 UID (SCHEDULERINFO.UID 참조)',
  `TRIALKEY` varchar(20) NOT NULL COMMENT '스케쥴KEY값 schedulerinfo.TRIALKEY (예: 2426ST001)',
  `DECK` varchar(10) NOT NULL COMMENT 'DECK (A, B, C 등)',
  `ROOM_NO` varchar(20) NOT NULL COMMENT '방번호 (예: 101, 102, 201 등)',
  `ROOM_NAME` varchar(200) DEFAULT NULL COMMENT '방이름 (예: CREW1, PETTY, 2ND ENGINEER 등)',
  `TEL` varchar(20) DEFAULT NULL COMMENT '전화번호',
  `SIZE_M2` decimal(10,2) DEFAULT NULL COMMENT '크기(M2)',
  `BED_COUNT` int(11) DEFAULT NULL COMMENT '침대수',
  `BATHROOM_YN` varchar(20) DEFAULT NULL COMMENT '화장실 여부 (Y:있음, N:없음)',
  `STATUS` varchar(20) DEFAULT 'AVAILABLE' COMMENT '상태 (AVAILABLE:사용가능, OCCUPIED:사용중, MAINTENANCE:점검중)',
  `DEL_YN` varchar(20) DEFAULT 'N' COMMENT '삭제여부 (Y:삭제, N:정상)',
  `ANDROID_ID` varchar(100) DEFAULT NULL COMMENT 'Android 기기 ID',
  `MOBILE_DEVICE_ID` varchar(100) DEFAULT NULL COMMENT '모바일 기기 ID',
  `INSERT_DATE` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
  `REG_USERNAME` varchar(200) DEFAULT NULL COMMENT '등록자',
  `UPDATE_DATE` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
  `UPDATE_USERNAME` varchar(200) DEFAULT NULL COMMENT '수정자',
  PRIMARY KEY (`UID`)
) ENGINE=InnoDB AUTO_INCREMENT=13 DEFAULT CHARSET=utf8 COMMENT='모바일 방정보 테이블';

commit;