drop table mobile_room_userlist;

CREATE TABLE `mobile_room_userlist` (
  `UID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '고유 ID',
  `PROJ_NO` varchar(20) NOT NULL COMMENT '호선 (예: SN2426)',
  `SCHEDULERINFOUID` int(11) DEFAULT NULL COMMENT '스케줄러 정보 UID (SCHEDULERINFO.UID 참조)',
  `TRIALKEY` varchar(20) NOT NULL COMMENT '스케쥴KEY값 schedulerinfo.TRIALKEY (예: 2426ST001)',
  `ROOM_NO` varchar(20) NOT NULL COMMENT '방번호 (예: 101, 102 등)',
  `DEPARTMENT` varchar(100) DEFAULT NULL COMMENT '부서 (예: 기장운전)',
  `NAME` varchar(100) NOT NULL COMMENT '이름',
  `PHONE` varchar(20) DEFAULT NULL COMMENT '휴대폰번호',
  `USER_UID` int(11) DEFAULT NULL COMMENT '사용자 UID (시스템 연동용)',
  `CHECK_IN_DATE` date DEFAULT NULL COMMENT '방사용 시작일',
  `CHECK_OUT_DATE` date DEFAULT NULL COMMENT '방사용 종료일',
  `STATUS` varchar(20) DEFAULT 'CHECKED_IN' COMMENT '상태 (CHECKED_IN:입실, CHECKED_OUT:퇴실, RESERVED:예약)',
  `DEL_YN` varchar(2) DEFAULT 'N' COMMENT '삭제여부 (Y:삭제, N:정상)',
  `ANDROID_ID` varchar(100) DEFAULT NULL COMMENT 'Android 기기 ID',
  `MOBILE_DEVICE_ID` varchar(100) DEFAULT NULL COMMENT '모바일 기기 ID',
  `INSERT_DATE` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
  `REG_USERNAME` varchar(200) DEFAULT NULL COMMENT '등록자',
  `UPDATE_DATE` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
  `UPDATE_USERNAME` varchar(200) DEFAULT NULL COMMENT '수정자',
  PRIMARY KEY (`UID`)
) ENGINE=InnoDB AUTO_INCREMENT=14 DEFAULT CHARSET=utf8 COMMENT='모바일 방배정명단 테이블';
commit;